apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: erp-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: erp-web
  template:
    metadata:
      labels:
        app: erp-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
