apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: erp-redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: erp-redis
  template:
    metadata:
      labels:
        app: erp-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
